[package]
name = "day1"
version = "0.1.0"
authors = ["Danielle Brook-Roberge <danielle@brook-roberge.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
